# Generated by Django 2.1 on 2018-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tarefa')),
                ('done', models.BooleanField(blank=True, default=False, verbose_name='Feito')),
                ('dtcreate', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dtdone', models.DateField(blank=True, null=True, verbose_name='Data de Finalização')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
